version: '3.7'
services:
  db:
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE:      "${MONGO_INITDB_DATABASE}"
    volumes:
      - ./mongodb_data:/data/db
    image: 'mongo:latest'
    ports:
      - '27100:27017'
