version: "3.7"
services:
    mfs.db:
        image: 'mongo:latest'
        ports:
            - '27100:27017'
        volumes:
            - ./mongodb_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
            MONGO_INITDB_DATABASE:      "${MONGO_INITDB_DATABASE}"
        networks: 
            - database
            - amqp
    # mfs.api:
    #     build: "./MicroFileServer"
    #     container_name: "mfs.api"
    #     volumes:
    #       - "./.env:/root/.env"
    #     ports:
    #       - 8081:8081
    #     networks:
    #       - database
    mfs.amqp:
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
          - 5672:5672
          - 15672:15672
        networks:
          - amqp



networks: 
    database:
        driver: "bridge"
    amqp:
        driver: "bridge"