version: "3.7"
services:
    mfs.db:
        image: 'mongo:latest'
        ports:
            - '27100:27017'
        volumes:
            - ./mongodb_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
            MONGO_INITDB_DATABASE:      "${MONGO_INITDB_DATABASE}"
        networks: 
            - database


networks: 
    database:
        driver: "bridge"